# This rule is not used by the project greeting-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.simple1.k8s.operators.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: greeting-operator
    app.kubernetes.io/managed-by: kustomize
  name: greeting-admin-role
rules:
- apiGroups:
  - apps.simple1.k8s.operators.com
  resources:
  - greetings
  verbs:
  - '*'
- apiGroups:
  - apps.simple1.k8s.operators.com
  resources:
  - greetings/status
  verbs:
  - get
